### ISSUE TITLE
How to get infererced internal nodes' expression data?

### ISSUE THREAD

**Issue by kunwang34** [khalilouardini/treeVAE-reproducibility#3]
Hi,

I read your article and found that treeVAE is a very smart idea. I'm trying to use your code to analyze some real data but I don't know how to get inferenced results, such as the internal nodes' expression matrix.  Could you please give me some examples? 

Many Thanks.

**Comment by khalilouardini** [comment]
Hello, thanks for reaching out!

The notebook [scvi/external/notebooks/Metastasis.ipynb] shows how to train treeVAE on a real dataset. But on this notebook, only some training metrics are shown.

To run inference and get imputed internal states, you have to create a TreePosterior object after training (defined in a [scvi/external/inference/tree_inference.py]) and use the 'imputation_internal' function.

To give an example, after training treeVAE and creating the TreePosterior object (refer to Metastasis.ipynb notebook), inference would look like this:

`      # 1. ========== treeVAE imputations ===================
        # empirical library size (computed from the training data if available, otherwise set to 1000)
        empirical_l = np.mean(np.sum(X, axis=1))

        imputed = {}
        imputed_z = {}
        for n in self.tree.traverse('levelorder'):
            if not n.is_leaf():
                # x and z are the inferred gene expression, and the inferred latent state of the internal node
                x , z = self.tree_posterior.imputation_internal(n,
                                                            give_mean=False,
                                                            library_size=empirical_l
                                                            )
                imputed[n.name] = x
                imputed_z[n.name] = z
`
